Repository DOSOPT-CDS-WEB-4/CGV-SERVER, pull requests merged in 2023-11, with the labels that each got.

#9 [Feat] #8 - 결제하기 기능 API 구현
  cgv/src/main/java/org/sopt/server/cgv/controller/ScheduleController.java
  cgv/src/main/java/org/sopt/server/cgv/domain/Schedule.java
  cgv/src/main/java/org/sopt/server/cgv/dto/request/ReserveRequestDto.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/ReserveResponseDto.java
  cgv/src/main/java/org/sopt/server/cgv/global/response/ApiResponse.java
  cgv/src/main/java/org/sopt/server/cgv/global/response/ErrorType.java
  cgv/src/main/java/org/sopt/server/cgv/global/response/SuccessType.java
  cgv/src/main/java/org/sopt/server/cgv/repository/ScheduleRepository.java
  cgv/src/main/java/org/sopt/server/cgv/service/ScheduleService.java
Labels: 영린, API

#11 [ Chore] #10 - Movie 엔티티에 배경이미지 필드 추가
  cgv/src/main/java/org/sopt/server/cgv/domain/Movie.java
Labels: 영린, Chore

#12 [Feat] #6 - 빠른 예매 API 구현
  cgv/src/main/java/org/sopt/server/cgv/controller/ReservationController.java
  cgv/src/main/java/org/sopt/server/cgv/domain/RegionName.java
  cgv/src/main/java/org/sopt/server/cgv/domain/Schedule.java
  cgv/src/main/java/org/sopt/server/cgv/domain/Screen.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/MovieScreenScheduleResponseDto.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/QuickReservationResponseDto.java
  cgv/src/main/java/org/sopt/server/cgv/global/response/ErrorType.java
  cgv/src/main/java/org/sopt/server/cgv/global/response/SuccessType.java
  cgv/src/main/java/org/sopt/server/cgv/repository/MovieRepository.java
  cgv/src/main/java/org/sopt/server/cgv/repository/RegionRepository.java
  cgv/src/main/java/org/sopt/server/cgv/repository/ScheduleRepository.java
  cgv/src/main/java/org/sopt/server/cgv/repository/ScreenRepository.java
  cgv/src/main/java/org/sopt/server/cgv/service/MovieService.java
  cgv/src/main/java/org/sopt/server/cgv/service/RegionService.java
  cgv/src/main/java/org/sopt/server/cgv/service/ScheduleService.java
  cgv/src/main/java/org/sopt/server/cgv/service/ScreenService.java
Labels: 찬, API

#16 [Feat] 기존 빠른예매 API에 날짜 필터링 추가
  cgv/.gitignore
  cgv/src/main/java/org/sopt/server/cgv/controller/ReservationController.java
  cgv/src/main/java/org/sopt/server/cgv/service/ScheduleService.java
  cgv/src/main/resources/application.yml
Labels: 찬, API, Chore

#18 [Docs] #17 - .gitignore 설정 변경
  cgv/.gitignore
  cgv/gradle/wrapper/gradle-wrapper.jar
Labels: 영린, Chore

#21 [Feat] #20 - 상영관 중복 선택 구현
  cgv/src/main/java/org/sopt/server/cgv/controller/RegionController.java
  cgv/src/main/java/org/sopt/server/cgv/controller/ReservationController.java
  cgv/src/main/java/org/sopt/server/cgv/controller/ScreenController.java
  cgv/src/main/java/org/sopt/server/cgv/service/ScreenService.java
Labels: 찬, API

#22 [Feat] Https 배포 및 CORS 에러 처리를 위한 파일 추가
  cgv/src/main/java/org/sopt/server/cgv/global/config/SecurityConfig.java
  cgv/src/main/java/org/sopt/server/cgv/global/config/WebConfig.java
  cgv/src/main/resources/application.yml
Labels: 영린

#24 [Feat] #23 - 좋아요 및 좋아요 취소 API 구현
  cgv/src/main/java/org/sopt/server/cgv/controller/MovieController.java
  cgv/src/main/java/org/sopt/server/cgv/domain/Movie.java
  cgv/src/main/java/org/sopt/server/cgv/global/response/SuccessType.java
  cgv/src/main/java/org/sopt/server/cgv/service/MovieService.java
Labels: 찬, API

#26 [Fix] #25 - 로컬에서 401 뜨는 에러 수정
  cgv/src/main/java/org/sopt/server/cgv/controller/MovieController.java
  cgv/src/main/java/org/sopt/server/cgv/global/config/WebConfig.java
Labels: 찬, refactor, Fix

#28 [Refactor] #27 - 프론트 로컬 url cors에 추가
  cgv/src/main/java/org/sopt/server/cgv/global/config/WebConfig.java
Labels: 찬, refactor

#30 [Refactor] #29 - 빠른예매 API에 schedule_id 추가
  cgv/src/main/java/org/sopt/server/cgv/dto/response/MovieInfoResponseDto.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/MovieScreenScheduleResponseDto.java
Labels: 찬, refactor

#32 [Chore] #31 - 빠른 예매 API 클라 측 요청 사항 반영
  cgv/src/main/java/org/sopt/server/cgv/controller/ReservationController.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/MovieInfoResponseDto.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/MovieScreenScheduleResponseDto.java
  cgv/src/main/java/org/sopt/server/cgv/dto/response/QuickReservationResponseDto.java
Labels: 영린, Chore

#34 [Refactor] #33 - 빠른 예매 API에서 일주일치 상영 스케쥴 전달
  cgv/src/main/java/org/sopt/server/cgv/controller/ReservationController.java
  cgv/src/main/java/org/sopt/server/cgv/service/ScheduleService.java
Labels: 찬, refactor
